//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Service.FandP.PriceCalculator.TIAReferenceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_reference_request", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_reference_request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string display_codeField;
        
        private string languageField;
        
        private string order_byField;
        
        private System.DateTime request_dateField;
        
        private System.Nullable<int> site_idField;
        
        private bool site_idSpecifiedField;
        
        private string table_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string display_code {
            get {
                return this.display_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.display_codeField, value) != true)) {
                    this.display_codeField = value;
                    this.RaisePropertyChanged("display_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string order_by {
            get {
                return this.order_byField;
            }
            set {
                if ((object.ReferenceEquals(this.order_byField, value) != true)) {
                    this.order_byField = value;
                    this.RaisePropertyChanged("order_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime request_date {
            get {
                return this.request_dateField;
            }
            set {
                if ((this.request_dateField.Equals(value) != true)) {
                    this.request_dateField = value;
                    this.RaisePropertyChanged("request_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> site_id {
            get {
                return this.site_idField;
            }
            set {
                if ((this.site_idField.Equals(value) != true)) {
                    this.site_idField = value;
                    this.RaisePropertyChanged("site_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool site_idSpecified {
            get {
                return this.site_idSpecifiedField;
            }
            set {
                if ((this.site_idSpecifiedField.Equals(value) != true)) {
                    this.site_idSpecifiedField = value;
                    this.RaisePropertyChanged("site_idSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string table_name {
            get {
                return this.table_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.table_nameField, value) != true)) {
                    this.table_nameField = value;
                    this.RaisePropertyChanged("table_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_reference_response", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_reference_response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_responseError_record error_recordField;
        
        private GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_responseReference_record[] reference_recordField;
        
        private string table_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_responseError_record error_record {
            get {
                return this.error_recordField;
            }
            set {
                if ((object.ReferenceEquals(this.error_recordField, value) != true)) {
                    this.error_recordField = value;
                    this.RaisePropertyChanged("error_record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_responseReference_record[] reference_record {
            get {
                return this.reference_recordField;
            }
            set {
                if ((object.ReferenceEquals(this.reference_recordField, value) != true)) {
                    this.reference_recordField = value;
                    this.RaisePropertyChanged("reference_record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string table_name {
            get {
                return this.table_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.table_nameField, value) != true)) {
                    this.table_nameField = value;
                    this.RaisePropertyChanged("table_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_reference_responseError_record", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_reference_responseError_record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string error_codeField;
        
        private string error_descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.error_codeField, value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string error_description {
            get {
                return this.error_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.error_descriptionField, value) != true)) {
                    this.error_descriptionField = value;
                    this.RaisePropertyChanged("error_description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_reference_responseReference_record", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_reference_responseReference_record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string display_codeField;
        
        private string help_textField;
        
        private string misc_valueField;
        
        private int sort_noField;
        
        private bool sort_noSpecifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string display_code {
            get {
                return this.display_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.display_codeField, value) != true)) {
                    this.display_codeField = value;
                    this.RaisePropertyChanged("display_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string help_text {
            get {
                return this.help_textField;
            }
            set {
                if ((object.ReferenceEquals(this.help_textField, value) != true)) {
                    this.help_textField = value;
                    this.RaisePropertyChanged("help_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string misc_value {
            get {
                return this.misc_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.misc_valueField, value) != true)) {
                    this.misc_valueField = value;
                    this.RaisePropertyChanged("misc_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sort_no {
            get {
                return this.sort_noField;
            }
            set {
                if ((this.sort_noField.Equals(value) != true)) {
                    this.sort_noField = value;
                    this.RaisePropertyChanged("sort_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool sort_noSpecified {
            get {
                return this.sort_noSpecifiedField;
            }
            set {
                if ((this.sort_noSpecifiedField.Equals(value) != true)) {
                    this.sort_noSpecifiedField = value;
                    this.RaisePropertyChanged("sort_noSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_pe_reference_request", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_pe_reference_request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string display_codeField;
        
        private string indexedField;
        
        private string languageField;
        
        private string order_byField;
        
        private string product_idField;
        
        private string table_nameField;
        
        private System.Nullable<int> versionField;
        
        private bool versionSpecifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string display_code {
            get {
                return this.display_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.display_codeField, value) != true)) {
                    this.display_codeField = value;
                    this.RaisePropertyChanged("display_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string indexed {
            get {
                return this.indexedField;
            }
            set {
                if ((object.ReferenceEquals(this.indexedField, value) != true)) {
                    this.indexedField = value;
                    this.RaisePropertyChanged("indexed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string order_by {
            get {
                return this.order_byField;
            }
            set {
                if ((object.ReferenceEquals(this.order_byField, value) != true)) {
                    this.order_byField = value;
                    this.RaisePropertyChanged("order_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string product_id {
            get {
                return this.product_idField;
            }
            set {
                if ((object.ReferenceEquals(this.product_idField, value) != true)) {
                    this.product_idField = value;
                    this.RaisePropertyChanged("product_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string table_name {
            get {
                return this.table_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.table_nameField, value) != true)) {
                    this.table_nameField = value;
                    this.RaisePropertyChanged("table_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> version {
            get {
                return this.versionField;
            }
            set {
                if ((this.versionField.Equals(value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool versionSpecified {
            get {
                return this.versionSpecifiedField;
            }
            set {
                if ((this.versionSpecifiedField.Equals(value) != true)) {
                    this.versionSpecifiedField = value;
                    this.RaisePropertyChanged("versionSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_pe_reference_response", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_pe_reference_response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_responseError_record error_recordField;
        
        private GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_responseReference_record[] reference_recordField;
        
        private string table_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_responseError_record error_record {
            get {
                return this.error_recordField;
            }
            set {
                if ((object.ReferenceEquals(this.error_recordField, value) != true)) {
                    this.error_recordField = value;
                    this.RaisePropertyChanged("error_record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_responseReference_record[] reference_record {
            get {
                return this.reference_recordField;
            }
            set {
                if ((object.ReferenceEquals(this.reference_recordField, value) != true)) {
                    this.reference_recordField = value;
                    this.RaisePropertyChanged("reference_record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string table_name {
            get {
                return this.table_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.table_nameField, value) != true)) {
                    this.table_nameField = value;
                    this.RaisePropertyChanged("table_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_pe_reference_responseError_record", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_pe_reference_responseError_record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string error_codeField;
        
        private string error_descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.error_codeField, value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string error_description {
            get {
                return this.error_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.error_descriptionField, value) != true)) {
                    this.error_descriptionField = value;
                    this.RaisePropertyChanged("error_description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xla_pe_reference_responseReference_record", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class xla_pe_reference_responseReference_record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string display_codeField;
        
        private string help_textField;
        
        private int sort_noField;
        
        private bool sort_noSpecifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string display_code {
            get {
                return this.display_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.display_codeField, value) != true)) {
                    this.display_codeField = value;
                    this.RaisePropertyChanged("display_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string help_text {
            get {
                return this.help_textField;
            }
            set {
                if ((object.ReferenceEquals(this.help_textField, value) != true)) {
                    this.help_textField = value;
                    this.RaisePropertyChanged("help_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sort_no {
            get {
                return this.sort_noField;
            }
            set {
                if ((this.sort_noField.Equals(value) != true)) {
                    this.sort_noField = value;
                    this.RaisePropertyChanged("sort_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool sort_noSpecified {
            get {
                return this.sort_noSpecifiedField;
            }
            set {
                if ((this.sort_noSpecifiedField.Equals(value) != true)) {
                    this.sort_noSpecifiedField = value;
                    this.RaisePropertyChanged("sort_noSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tariff_codes_request", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class tariff_codes_request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string indexedField;
        
        private string order_byField;
        
        private string product_line_idField;
        
        private int roundField;
        
        private bool roundSpecifiedField;
        
        private string table_nameField;
        
        private System.Nullable<int> versionField;
        
        private bool versionSpecifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string indexed {
            get {
                return this.indexedField;
            }
            set {
                if ((object.ReferenceEquals(this.indexedField, value) != true)) {
                    this.indexedField = value;
                    this.RaisePropertyChanged("indexed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string order_by {
            get {
                return this.order_byField;
            }
            set {
                if ((object.ReferenceEquals(this.order_byField, value) != true)) {
                    this.order_byField = value;
                    this.RaisePropertyChanged("order_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string product_line_id {
            get {
                return this.product_line_idField;
            }
            set {
                if ((object.ReferenceEquals(this.product_line_idField, value) != true)) {
                    this.product_line_idField = value;
                    this.RaisePropertyChanged("product_line_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int round {
            get {
                return this.roundField;
            }
            set {
                if ((this.roundField.Equals(value) != true)) {
                    this.roundField = value;
                    this.RaisePropertyChanged("round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool roundSpecified {
            get {
                return this.roundSpecifiedField;
            }
            set {
                if ((this.roundSpecifiedField.Equals(value) != true)) {
                    this.roundSpecifiedField = value;
                    this.RaisePropertyChanged("roundSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string table_name {
            get {
                return this.table_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.table_nameField, value) != true)) {
                    this.table_nameField = value;
                    this.RaisePropertyChanged("table_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> version {
            get {
                return this.versionField;
            }
            set {
                if ((this.versionField.Equals(value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool versionSpecified {
            get {
                return this.versionSpecifiedField;
            }
            set {
                if ((this.versionSpecifiedField.Equals(value) != true)) {
                    this.versionSpecifiedField = value;
                    this.RaisePropertyChanged("versionSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tariff_codes_response", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class tariff_codes_response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_responseError_record error_recordField;
        
        private string table_nameField;
        
        private GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_responseTariff_code_record[] tariff_code_recordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_responseError_record error_record {
            get {
                return this.error_recordField;
            }
            set {
                if ((object.ReferenceEquals(this.error_recordField, value) != true)) {
                    this.error_recordField = value;
                    this.RaisePropertyChanged("error_record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string table_name {
            get {
                return this.table_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.table_nameField, value) != true)) {
                    this.table_nameField = value;
                    this.RaisePropertyChanged("table_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_responseTariff_code_record[] tariff_code_record {
            get {
                return this.tariff_code_recordField;
            }
            set {
                if ((object.ReferenceEquals(this.tariff_code_recordField, value) != true)) {
                    this.tariff_code_recordField = value;
                    this.RaisePropertyChanged("tariff_code_record");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tariff_codes_responseError_record", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class tariff_codes_responseError_record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string error_codeField;
        
        private string error_descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string error_code {
            get {
                return this.error_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.error_codeField, value) != true)) {
                    this.error_codeField = value;
                    this.RaisePropertyChanged("error_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string error_description {
            get {
                return this.error_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.error_descriptionField, value) != true)) {
                    this.error_descriptionField = value;
                    this.RaisePropertyChanged("error_description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tariff_codes_responseTariff_code_record", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class tariff_codes_responseTariff_code_record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string max_valField;
        
        private string min_valField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string max_val {
            get {
                return this.max_valField;
            }
            set {
                if ((object.ReferenceEquals(this.max_valField, value) != true)) {
                    this.max_valField = value;
                    this.RaisePropertyChanged("max_val");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string min_val {
            get {
                return this.min_valField;
            }
            set {
                if ((object.ReferenceEquals(this.min_valField, value) != true)) {
                    this.min_valField = value;
                    this.RaisePropertyChanged("min_val");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gf_club_request", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class gf_club_request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string company_profession_codeField;
        
        private string zip_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string company_profession_code {
            get {
                return this.company_profession_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.company_profession_codeField, value) != true)) {
                    this.company_profession_codeField = value;
                    this.RaisePropertyChanged("company_profession_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string zip_code {
            get {
                return this.zip_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.zip_codeField, value) != true)) {
                    this.zip_codeField = value;
                    this.RaisePropertyChanged("zip_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gf_club_response", Namespace="http://schemas.datacontract.org/2004/07/GF.Service.TIA.Reference.DOM")]
    [System.SerializableAttribute()]
    public partial class gf_club_response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string club_nameField;
        
        private int club_numberField;
        
        private string transport_assistanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string club_name {
            get {
                return this.club_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.club_nameField, value) != true)) {
                    this.club_nameField = value;
                    this.RaisePropertyChanged("club_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int club_number {
            get {
                return this.club_numberField;
            }
            set {
                if ((this.club_numberField.Equals(value) != true)) {
                    this.club_numberField = value;
                    this.RaisePropertyChanged("club_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string transport_assistance {
            get {
                return this.transport_assistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.transport_assistanceField, value) != true)) {
                    this.transport_assistanceField = value;
                    this.RaisePropertyChanged("transport_assistance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TIAReferenceClient.ITIAReferenceService")]
    public interface ITIAReferenceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetXlaReference", ReplyAction="http://tempuri.org/ITIAReferenceService/GetXlaReferenceResponse")]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceResponse GetXlaReference(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetXlaReference", ReplyAction="http://tempuri.org/ITIAReferenceService/GetXlaReferenceResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceResponse> GetXlaReferenceAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetXlaPeReference", ReplyAction="http://tempuri.org/ITIAReferenceService/GetXlaPeReferenceResponse")]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceResponse GetXlaPeReference(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetXlaPeReference", ReplyAction="http://tempuri.org/ITIAReferenceService/GetXlaPeReferenceResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceResponse> GetXlaPeReferenceAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetTariffCode", ReplyAction="http://tempuri.org/ITIAReferenceService/GetTariffCodeResponse")]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeResponse GetTariffCode(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetTariffCode", ReplyAction="http://tempuri.org/ITIAReferenceService/GetTariffCodeResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeResponse> GetTariffCodeAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetClubNumber", ReplyAction="http://tempuri.org/ITIAReferenceService/GetClubNumberResponse")]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberResponse GetClubNumber(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITIAReferenceService/GetClubNumber", ReplyAction="http://tempuri.org/ITIAReferenceService/GetClubNumberResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberResponse> GetClubNumberAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlaReference", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlaReferenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_request req;
        
        public GetXlaReferenceRequest() {
        }
        
        public GetXlaReferenceRequest(GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlaReferenceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlaReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetXlaReferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_response res;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error;
        
        public GetXlaReferenceResponse() {
        }
        
        public GetXlaReferenceResponse(bool GetXlaReferenceResult, GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_response res, string error) {
            this.GetXlaReferenceResult = GetXlaReferenceResult;
            this.res = res;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlaPeReference", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlaPeReferenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_request req;
        
        public GetXlaPeReferenceRequest() {
        }
        
        public GetXlaPeReferenceRequest(GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXlaPeReferenceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXlaPeReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetXlaPeReferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_response res;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error;
        
        public GetXlaPeReferenceResponse() {
        }
        
        public GetXlaPeReferenceResponse(bool GetXlaPeReferenceResult, GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_response res, string error) {
            this.GetXlaPeReferenceResult = GetXlaPeReferenceResult;
            this.res = res;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTariffCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTariffCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_request req;
        
        public GetTariffCodeRequest() {
        }
        
        public GetTariffCodeRequest(GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTariffCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTariffCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetTariffCodeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_response res;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error;
        
        public GetTariffCodeResponse() {
        }
        
        public GetTariffCodeResponse(bool GetTariffCodeResult, GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_response res, string error) {
            this.GetTariffCodeResult = GetTariffCodeResult;
            this.res = res;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClubNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClubNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.gf_club_request req;
        
        public GetClubNumberRequest() {
        }
        
        public GetClubNumberRequest(GF.Service.FandP.PriceCalculator.TIAReferenceClient.gf_club_request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClubNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetClubNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetClubNumberResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public GF.Service.FandP.PriceCalculator.TIAReferenceClient.gf_club_response res;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error;
        
        public GetClubNumberResponse() {
        }
        
        public GetClubNumberResponse(bool GetClubNumberResult, GF.Service.FandP.PriceCalculator.TIAReferenceClient.gf_club_response res, string error) {
            this.GetClubNumberResult = GetClubNumberResult;
            this.res = res;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITIAReferenceServiceChannel : GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TIAReferenceServiceClient : System.ServiceModel.ClientBase<GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService>, GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService {
        
        public TIAReferenceServiceClient() {
        }
        
        public TIAReferenceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TIAReferenceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TIAReferenceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TIAReferenceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceResponse GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService.GetXlaReference(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceRequest request) {
            return base.Channel.GetXlaReference(request);
        }
        
        public bool GetXlaReference(GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_request req, out GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_reference_response res, out string error) {
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceRequest inValue = new GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceRequest();
            inValue.req = req;
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceResponse retVal = ((GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService)(this)).GetXlaReference(inValue);
            res = retVal.res;
            error = retVal.error;
            return retVal.GetXlaReferenceResult;
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceResponse> GetXlaReferenceAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaReferenceRequest request) {
            return base.Channel.GetXlaReferenceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceResponse GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService.GetXlaPeReference(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceRequest request) {
            return base.Channel.GetXlaPeReference(request);
        }
        
        public bool GetXlaPeReference(GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_request req, out GF.Service.FandP.PriceCalculator.TIAReferenceClient.xla_pe_reference_response res, out string error) {
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceRequest inValue = new GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceRequest();
            inValue.req = req;
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceResponse retVal = ((GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService)(this)).GetXlaPeReference(inValue);
            res = retVal.res;
            error = retVal.error;
            return retVal.GetXlaPeReferenceResult;
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceResponse> GetXlaPeReferenceAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetXlaPeReferenceRequest request) {
            return base.Channel.GetXlaPeReferenceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeResponse GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService.GetTariffCode(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeRequest request) {
            return base.Channel.GetTariffCode(request);
        }
        
        public bool GetTariffCode(GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_request req, out GF.Service.FandP.PriceCalculator.TIAReferenceClient.tariff_codes_response res, out string error) {
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeRequest inValue = new GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeRequest();
            inValue.req = req;
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeResponse retVal = ((GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService)(this)).GetTariffCode(inValue);
            res = retVal.res;
            error = retVal.error;
            return retVal.GetTariffCodeResult;
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeResponse> GetTariffCodeAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetTariffCodeRequest request) {
            return base.Channel.GetTariffCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberResponse GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService.GetClubNumber(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberRequest request) {
            return base.Channel.GetClubNumber(request);
        }
        
        public bool GetClubNumber(GF.Service.FandP.PriceCalculator.TIAReferenceClient.gf_club_request req, out GF.Service.FandP.PriceCalculator.TIAReferenceClient.gf_club_response res, out string error) {
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberRequest inValue = new GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberRequest();
            inValue.req = req;
            GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberResponse retVal = ((GF.Service.FandP.PriceCalculator.TIAReferenceClient.ITIAReferenceService)(this)).GetClubNumber(inValue);
            res = retVal.res;
            error = retVal.error;
            return retVal.GetClubNumberResult;
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberResponse> GetClubNumberAsync(GF.Service.FandP.PriceCalculator.TIAReferenceClient.GetClubNumberRequest request) {
            return base.Channel.GetClubNumberAsync(request);
        }
    }
}
