//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace GF.Service.FandP.PriceCalc.DOM {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class request {
        
        /// <remarks/>
        public requestCustomer customer;
        
        /// <remarks/>
        public ProduktType insurancerequestsforcalculation;
        
        /// <remarks/>
        public string sessionid;
        
        /// <remarks/>
        public requestInsurancerequest insurancerequest;
        
        /// <remarks/>
        public int affinity_no;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemaVersion;
        
        public request() {
            this.affinity_no = 0;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestCustomer {
        
        /// <remarks/>
        public ushort alder;
        
        /// <remarks/>
        public ushort postnr;
        
        /// <remarks/>
        public string adresse;
        
        /// <remarks/>
        public string kvhx;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum ProduktType {
        
        /// <remarks/>
        bil,
        
        /// <remarks/>
        hus,
        
        /// <remarks/>
        indbo,
        
        /// <remarks/>
        fritidshus,
        
        /// <remarks/>
        ulykke,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequest {
        
        /// <remarks/>
        public requestInsurancerequestBil bil;
        
        /// <remarks/>
        public requestInsurancerequestHus hus;
        
        /// <remarks/>
        public requestInsurancerequestIndbo indbo;
        
        /// <remarks/>
        public requestInsurancerequestFritidshus fritidshus;
        
        /// <remarks/>
        public requestInsurancerequestUlykke ulykke;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequestBil {
        
        /// <remarks/>
        public ushort koersel_aar;
        
        /// <remarks/>
        public string model;
        
        /// <remarks/>
        public ushort modelaar;
        
        /// <remarks/>
        public string motor;
        
        /// <remarks/>
        public string fabrikat;
        
        /// <remarks/>
        public ushort fabrikatkode;
        
        /// <remarks/>
        public ushort modelkode;
        
        /// <remarks/>
        public uint nypris;
        
        /// <remarks/>
        public ushort hk;
        
        /// <remarks/>
        public uint modelvariantid;
        
        /// <remarks/>
        public string variant;
        
        /// <remarks/>
        public string typenavn;
        
        /// <remarks/>
        public ushort egenvaegt;
        
        /// <remarks/>
        public ushort koereklarvaegt;
        
        /// <remarks/>
        public string dktypegodkendelsesnumre;
        
        /// <remarks/>
        public string drivmiddel;
        
        /// <remarks/>
        public ushort kw;
        
        /// <remarks/>
        public string stelnummer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime foerste_reg;
        
        /// <remarks/>
        public string reg_nr;
        
        /// <remarks/>
        public ulong kid;
        
        /// <remarks/>
        public bool ansvar_kasko;
        
        /// <remarks/>
        public ushort selvrisiko;
        
        /// <remarks/>
        public bool friskade;
        
        /// <remarks/>
        public bool brugere_u25;
        
        /// <remarks/>
        public bool udvidetglas;
        
        /// <remarks/>
        public bool fastpraemie;
        
        /// <remarks/>
        public bool foererdaekning;
        
        /// <remarks/>
        public bool privateleaset;
        
        /// <remarks/>
        public bool vejhjaelp;
        
        /// <remarks/>
        public ushort antalaarmedbilforsikring;
        
        /// <remarks/>
        public ushort antalskader;
        
        /// <remarks/>
        public ushort skade1;
        
        /// <remarks/>
        public ushort skade2;
        
        /// <remarks/>
        public ushort skade3;
        
        /// <remarks/>
        public bool klipikoerekort;
        
        /// <remarks/>
        public string rabatordningvalg;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequestHus {
        
        /// <remarks/>
        public ushort opfoerelsesaar;
        
        /// <remarks/>
        public ushort bebygget_m2;
        
        /// <remarks/>
        public ushort bolig_m2;
        
        /// <remarks/>
        public ushort garage_m2;
        
        /// <remarks/>
        public ushort etager;
        
        /// <remarks/>
        public RoofingMaterialCodeType tagbeklaedning;
        
        /// <remarks/>
        public ushort kaelder_m2;
        
        /// <remarks/>
        public ushort antal_skader_treaar;
        
        /// <remarks/>
        public HeatingCodeType opvarmning;
        
        /// <remarks/>
        public ushort pool_m2;
        
        /// <remarks/>
        public PoolPlaceringType pool_placering;
        
        /// <remarks/>
        public bool vandstop;
        
        /// <remarks/>
        public bool hoejvandslukke;
        
        /// <remarks/>
        public bool nedlagt_landbrug;
        
        /// <remarks/>
        public ushort toiletbadrum;
        
        /// <remarks/>
        public bool straatag_brandisoleret;
        
        /// <remarks/>
        public bool udvidetvand;
        
        /// <remarks/>
        public bool dyrskader;
        
        /// <remarks/>
        public bool kosmetiskdaekning;
        
        /// <remarks/>
        public bool svampinsekt;
        
        /// <remarks/>
        public bool raad;
        
        /// <remarks/>
        public bool roerkablerstikledninger;
        
        /// <remarks/>
        public ushort selvrisiko;
        
        /// <remarks/>
        public string rabatordningvalg;
        
        /// <remarks/>
        public UseCodeType bo_type;
        
        /// <remarks/>
        public OuterWallsMaterialCodeType ydervaeg_kode;
        
        /// <remarks/>
        public ushort kaelder_lovlig_m2;
        
        /// <remarks/>
        public HeatingInstallationCodeType varmeinstallation;
        
        /// <remarks/>
        public ushort erhverv_m2;
        
        /// <remarks/>
        public ushort lejligheder;
        
        /// <remarks/>
        public ushort overdaek_m2;
        
        /// <remarks/>
        public ushort tagetage_lovlig_m2;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum RoofingMaterialCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum HeatingCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum PoolPlaceringType {
        
        /// <remarks/>
        indendoers,
        
        /// <remarks/>
        udendoers,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum UseCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("110")]
        Item110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("120")]
        Item120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("140")]
        Item140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("150")]
        Item150,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("160")]
        Item160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("190")]
        Item190,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("210")]
        Item210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("220")]
        Item220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("230")]
        Item230,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("290")]
        Item290,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("310")]
        Item310,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("320")]
        Item320,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("330")]
        Item330,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("390")]
        Item390,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("410")]
        Item410,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("420")]
        Item420,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("430")]
        Item430,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("440")]
        Item440,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("490")]
        Item490,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("510")]
        Item510,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("520")]
        Item520,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("530")]
        Item530,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("540")]
        Item540,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("590")]
        Item590,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("910")]
        Item910,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("920")]
        Item920,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("930")]
        Item930,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum OuterWallsMaterialCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum HeatingInstallationCodeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequestIndbo {
        
        /// <remarks/>
        public ushort antal_voksne;
        
        /// <remarks/>
        public ushort antal_boern;
        
        /// <remarks/>
        public ushort bolig_m2;
        
        /// <remarks/>
        public ushort antal_skader_treaar;
        
        /// <remarks/>
        public ushort kaelder_m2;
        
        /// <remarks/>
        public RoofingMaterialCodeType tagbeklaedning;
        
        /// <remarks/>
        public bool straatag_brandisoleret;
        
        /// <remarks/>
        public bool eksisterende_forsikring;
        
        /// <remarks/>
        public bool alarm;
        
        /// <remarks/>
        public bool tilknyttet_alarmcentral;
        
        /// <remarks/>
        public bool vindueslaas;
        
        /// <remarks/>
        public bool roegalarm;
        
        /// <remarks/>
        public bool glaskumme;
        
        /// <remarks/>
        public bool pludseligskade;
        
        /// <remarks/>
        public bool elektronik;
        
        /// <remarks/>
        public bool rejseverden;
        
        /// <remarks/>
        public bool rejseeuropa;
        
        /// <remarks/>
        public bool afbestillingsforsikring;
        
        /// <remarks/>
        public uint indbosum;
        
        /// <remarks/>
        public ushort selvrisiko;
        
        /// <remarks/>
        public string rabatordningvalg;
        
        /// <remarks/>
        public UseCodeType bo_type;
        
        /// <remarks/>
        public OuterWallsMaterialCodeType ydervaeg_kode;
        
        /// <remarks/>
        public ushort erhverv_m2;
        
        /// <remarks/>
        public ushort lejligheder;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequestFritidshus {
        
        /// <remarks/>
        public string fritidshus_adresse;
        
        /// <remarks/>
        public string fritidshus_kvhx;
        
        /// <remarks/>
        public ushort fritidshus_postnr;
        
        /// <remarks/>
        public ushort opfoerelsesaar;
        
        /// <remarks/>
        public ushort bebygget_m2;
        
        /// <remarks/>
        public ushort bolig_m2;
        
        /// <remarks/>
        public ushort garage_m2;
        
        /// <remarks/>
        public ushort etager;
        
        /// <remarks/>
        public ushort toiletbadrum;
        
        /// <remarks/>
        public HeatingCodeType opvarmning;
        
        /// <remarks/>
        public bool braendeovn;
        
        /// <remarks/>
        public RoofingMaterialCodeType tagbeklaedning;
        
        /// <remarks/>
        public bool straatag_brandisoleret;
        
        /// <remarks/>
        public bool nedlagt_landbrug;
        
        /// <remarks/>
        public PoolPlaceringType pool_placering;
        
        /// <remarks/>
        public ushort pool_m2;
        
        /// <remarks/>
        public uint indbosum;
        
        /// <remarks/>
        public ushort selvrisiko;
        
        /// <remarks/>
        public bool svampinsekt;
        
        /// <remarks/>
        public bool raad;
        
        /// <remarks/>
        public bool roerstikledninger;
        
        /// <remarks/>
        public bool kosmetiskdaekning;
        
        /// <remarks/>
        public bool lejerskader;
        
        /// <remarks/>
        public bool elektronik;
        
        /// <remarks/>
        public bool udlejes;
        
        /// <remarks/>
        public string rabatordningvalg;
        
        /// <remarks/>
        public ushort antal_skader_treaar;
        
        /// <remarks/>
        public UseCodeType bo_type;
        
        /// <remarks/>
        public OuterWallsMaterialCodeType ydervaeg_kode;
        
        /// <remarks/>
        public ushort kaelder_lovlig_m2;
        
        /// <remarks/>
        public HeatingInstallationCodeType varmeinstallation;
        
        /// <remarks/>
        public ushort erhverv_m2;
        
        /// <remarks/>
        public ushort lejligheder;
        
        /// <remarks/>
        public ushort overdaek_m2;
        
        /// <remarks/>
        public ushort tagetage_lovlig_m2;
        
        /// <remarks/>
        public ushort kaelder_m2;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequestUlykke {
        
        /// <remarks/>
        public string stillingsbetegnelse;
        
        /// <remarks/>
        public uint stillingsbetegnelseId;
        
        /// <remarks/>
        public bool heltidsulykke;
        
        /// <remarks/>
        public uint forsikringssum_varigt_men;
        
        /// <remarks/>
        public uint forsikringssum_doed;
        
        /// <remarks/>
        public bool dobbelterstatning;
        
        /// <remarks/>
        public bool farligsport;
        
        /// <remarks/>
        public bool motorcykelknallert;
        
        /// <remarks/>
        public bool strakserstatning;
        
        /// <remarks/>
        public requestInsurancerequestUlykkeSamlever samlever;
        
        /// <remarks/>
        public requestInsurancerequestUlykkeBoern boern;
        
        /// <remarks/>
        public string rabatordningvalg;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequestUlykkeSamlever {
        
        /// <remarks/>
        public ushort alder;
        
        /// <remarks/>
        public string stillingsbetegnelse;
        
        /// <remarks/>
        public uint stillingsbetegnelseId;
        
        /// <remarks/>
        public bool heltidsulykke;
        
        /// <remarks/>
        public uint forsikringssum_varigt_men;
        
        /// <remarks/>
        public uint forsikringssum_doed;
        
        /// <remarks/>
        public bool dobbelterstatning;
        
        /// <remarks/>
        public bool farligsport;
        
        /// <remarks/>
        public bool motorcykelknallert;
        
        /// <remarks/>
        public bool strakserstatning;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class requestInsurancerequestUlykkeBoern {
        
        /// <remarks/>
        public ushort antal_u18;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alder")]
        public ushort[] alder;
        
        /// <remarks/>
        public uint forsikringssum_varigt_men;
        
        /// <remarks/>
        public bool dobbelterstatning;
        
        /// <remarks/>
        public bool farligsport;
        
        /// <remarks/>
        public bool motorcykelknallert;
        
        /// <remarks/>
        public bool strakserstatning;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class response {
        
        /// <remarks/>
        public uint statuscode;
        
        /// <remarks/>
        public string statusmessage;
        
        /// <remarks/>
        public string statusdetail;
        
        /// <remarks/>
        public responseIngenprisgrund ingenprisgrund;
        
        /// <remarks/>
        public responseProdukt produkt;
        
        /// <remarks/>
        public responseBil bil;
        
        /// <remarks/>
        public responseHus hus;
        
        /// <remarks/>
        public responseIndbo indbo;
        
        /// <remarks/>
        public responseFritidshus fritidshus;
        
        /// <remarks/>
        public responseUlykke ulykke;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemaVersion;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseIngenprisgrund {
        
        /// <remarks/>
        public bool tilvalg1;
        
        /// <remarks/>
        public bool tilvalg2;
        
        /// <remarks/>
        public bool tilvalg3;
        
        /// <remarks/>
        public bool tilvalg4;
        
        /// <remarks/>
        public bool tilvalg5;
        
        /// <remarks/>
        public bool tilvalg6;
        
        /// <remarks/>
        public bool andet;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseProdukt {
        
        /// <remarks/>
        public string produktnavn;
        
        /// <remarks/>
        public double produktpris;
        
        /// <remarks/>
        public string produktpris_forudsaetninger;
        
        /// <remarks/>
        public double produktsamlerabat;
        
        /// <remarks/>
        public string produktsamlerabat_forudsaetninger;
        
        /// <remarks/>
        public bool tilbagebetaling_af_praemie;
        
        /// <remarks/>
        public string yderligere_information;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseBil {
        
        /// <remarks/>
        public double selvrisiko;
        
        /// <remarks/>
        public bool ansvar_kasko;
        
        /// <remarks/>
        public bool vejhjaelp;
        
        /// <remarks/>
        public bool friskade;
        
        /// <remarks/>
        public bool udvidetglas;
        
        /// <remarks/>
        public bool fastpraemie;
        
        /// <remarks/>
        public bool foererdaekning;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseHus {
        
        /// <remarks/>
        public double selvrisiko;
        
        /// <remarks/>
        public bool udvidetvand;
        
        /// <remarks/>
        public bool dyrskader;
        
        /// <remarks/>
        public bool kosmetiskdaekning;
        
        /// <remarks/>
        public bool svampinsekt;
        
        /// <remarks/>
        public bool raad;
        
        /// <remarks/>
        public bool roerkablerstikledninger;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseIndbo {
        
        /// <remarks/>
        public double sum;
        
        /// <remarks/>
        public double selvrisiko;
        
        /// <remarks/>
        public bool glaskumme;
        
        /// <remarks/>
        public bool pludseligskade;
        
        /// <remarks/>
        public bool elektronik;
        
        /// <remarks/>
        public bool rejseeuropa;
        
        /// <remarks/>
        public bool rejseverden;
        
        /// <remarks/>
        public bool afbestillingsforsikring;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseFritidshus {
        
        /// <remarks/>
        public double sum;
        
        /// <remarks/>
        public double selvrisiko;
        
        /// <remarks/>
        public bool svampinsekt;
        
        /// <remarks/>
        public bool raad;
        
        /// <remarks/>
        public bool roerstikledninger;
        
        /// <remarks/>
        public bool kosmetiskdaekning;
        
        /// <remarks/>
        public bool lejerskader;
        
        /// <remarks/>
        public bool elektronik;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class responseUlykke {
        
        /// <remarks/>
        public double produktpris_dig;
        
        /// <remarks/>
        public double produktpris_samlever;
        
        /// <remarks/>
        public double produktpris_born;
        
        /// <remarks/>
        public double sum_doed_dig;
        
        /// <remarks/>
        public double sum_doed_samlever;
        
        /// <remarks/>
        public double sum_varigt_men_dig;
        
        /// <remarks/>
        public double sum_varigt_men_samlever;
        
        /// <remarks/>
        public double sum_varigt_men_born;
        
        /// <remarks/>
        public bool dobbelterstatning;
        
        /// <remarks/>
        public bool farligsport;
        
        /// <remarks/>
        public bool motorcykelknallert;
        
        /// <remarks/>
        public bool strakserstatning;
    }
}
