//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Service.FandP.PriceCalculator.EmailClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailClient.ISendEmailService")]
    public interface ISendEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendEmailService/SendEmail", ReplyAction="http://tempuri.org/ISendEmailService/SendEmailResponse")]
        GF.Service.FandP.PriceCalculator.EmailClient.SendEmailResponse SendEmail(GF.Service.FandP.PriceCalculator.EmailClient.SendEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendEmailService/SendEmail", ReplyAction="http://tempuri.org/ISendEmailService/SendEmailResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.EmailClient.SendEmailResponse> SendEmailAsync(GF.Service.FandP.PriceCalculator.EmailClient.SendEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string mailfrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mailto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public bool isBodyHtml;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(string mailfrom, string mailto, string subject, string body, bool isBodyHtml) {
            this.mailfrom = mailfrom;
            this.mailto = mailto;
            this.subject = subject;
            this.body = body;
            this.isBodyHtml = isBodyHtml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(bool SendEmailResult, string error) {
            this.SendEmailResult = SendEmailResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendEmailServiceChannel : GF.Service.FandP.PriceCalculator.EmailClient.ISendEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailServiceClient : System.ServiceModel.ClientBase<GF.Service.FandP.PriceCalculator.EmailClient.ISendEmailService>, GF.Service.FandP.PriceCalculator.EmailClient.ISendEmailService {
        
        public SendEmailServiceClient() {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GF.Service.FandP.PriceCalculator.EmailClient.SendEmailResponse GF.Service.FandP.PriceCalculator.EmailClient.ISendEmailService.SendEmail(GF.Service.FandP.PriceCalculator.EmailClient.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public bool SendEmail(string mailfrom, string mailto, string subject, string body, bool isBodyHtml, out string error) {
            GF.Service.FandP.PriceCalculator.EmailClient.SendEmailRequest inValue = new GF.Service.FandP.PriceCalculator.EmailClient.SendEmailRequest();
            inValue.mailfrom = mailfrom;
            inValue.mailto = mailto;
            inValue.subject = subject;
            inValue.body = body;
            inValue.isBodyHtml = isBodyHtml;
            GF.Service.FandP.PriceCalculator.EmailClient.SendEmailResponse retVal = ((GF.Service.FandP.PriceCalculator.EmailClient.ISendEmailService)(this)).SendEmail(inValue);
            error = retVal.error;
            return retVal.SendEmailResult;
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.EmailClient.SendEmailResponse> SendEmailAsync(GF.Service.FandP.PriceCalculator.EmailClient.SendEmailRequest request) {
            return base.Channel.SendEmailAsync(request);
        }
    }
}
