//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Service.FandP.PriceCalculator.TIABBRClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BbrDataResponse", Namespace="http://schemas.datacontract.org/2004/07/BackendService.DTO")]
    [System.SerializableAttribute()]
    public partial class BbrDataResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GF.Service.FandP.PriceCalculator.TIABBRClient.InputAddress AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GF.Service.FandP.PriceCalculator.TIABBRClient.BbrData[] BbrDataEntriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GF.Service.FandP.PriceCalculator.TIABBRClient.ErrorInformation ErrorInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KvhxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GF.Service.FandP.PriceCalculator.TIABBRClient.InputAddress Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GF.Service.FandP.PriceCalculator.TIABBRClient.BbrData[] BbrDataEntries {
            get {
                return this.BbrDataEntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.BbrDataEntriesField, value) != true)) {
                    this.BbrDataEntriesField = value;
                    this.RaisePropertyChanged("BbrDataEntries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GF.Service.FandP.PriceCalculator.TIABBRClient.ErrorInformation ErrorInformation {
            get {
                return this.ErrorInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorInformationField, value) != true)) {
                    this.ErrorInformationField = value;
                    this.RaisePropertyChanged("ErrorInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kvhx {
            get {
                return this.KvhxField;
            }
            set {
                if ((object.ReferenceEquals(this.KvhxField, value) != true)) {
                    this.KvhxField = value;
                    this.RaisePropertyChanged("Kvhx");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputAddress", Namespace="http://schemas.datacontract.org/2004/07/BackendService.DTO")]
    [System.SerializableAttribute()]
    public partial class InputAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorApartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetLetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorApartment {
            get {
                return this.FloorApartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorApartmentField, value) != true)) {
                    this.FloorApartmentField = value;
                    this.RaisePropertyChanged("FloorApartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostArea {
            get {
                return this.PostAreaField;
            }
            set {
                if ((this.PostAreaField.Equals(value) != true)) {
                    this.PostAreaField = value;
                    this.RaisePropertyChanged("PostArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetLetter {
            get {
                return this.StreetLetterField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetLetterField, value) != true)) {
                    this.StreetLetterField = value;
                    this.RaisePropertyChanged("StreetLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNumber {
            get {
                return this.StreetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNumberField, value) != true)) {
                    this.StreetNumberField = value;
                    this.RaisePropertyChanged("StreetNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInformation", Namespace="http://schemas.datacontract.org/2004/07/BackendService.DTO")]
    [System.SerializableAttribute()]
    public partial class ErrorInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorOccuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorOccured {
            get {
                return this.ErrorOccuredField;
            }
            set {
                if ((this.ErrorOccuredField.Equals(value) != true)) {
                    this.ErrorOccuredField = value;
                    this.RaisePropertyChanged("ErrorOccured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BbrData", Namespace="http://schemas.datacontract.org/2004/07/BackendService.DTO")]
    [System.SerializableAttribute()]
    public partial class BbrData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalBeboelseslejlPaaEjendommenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalBeboelseslejlighederField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalBygningerPaaEjendommenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalEjerlejlPaaEjendommenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalEnhederPaaEjendommenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalErhvervsenhederPaaEjendommenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalEtagerIBygningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalSmaabygningerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AntalVaerelserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ArealAfSmaabygningerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BadeforholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BadeforholdKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BeboetArealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BebyggetArealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeliggenhedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BygningensAfloebsforholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BygningensAfloebsforholdKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BygningensAnvendelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BygningensAnvendelseKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BygningensVandforsyningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BygningensVandforsyningKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BygningsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeltaStatuskodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EjendommensAfloebsforholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EjendommensAfloebsforholdKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EjendommensVandforsyningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EjendommensVandforsyningKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EjerlavField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnhedAnvendelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnhedAnvendelseKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EnhedensArealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EnhedsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ErhvervsarealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsrEjendomsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FredningsforholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FredningsforholdKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HusnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KVHXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KaelderarealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoekkenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KoekkenKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KommuneKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatrikelarealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatrikelbogstavField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatrikelnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OmTilbygningsaarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OpdateringsdatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OpfoerelsesaarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpvarmningsformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpvarmningsformKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostdistriktsnavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostnummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletBebyggetArealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletBoligarealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletBoligarealIBygningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletBygningsarealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletBygningsareal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletErhvervsArealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletErhvervsarealIBygningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SamletTagarealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StednavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplerendeVarmekildeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplerendeVarmekildeKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagmaterialeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagmaterialeKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TilnaermetEtagearealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToiletforholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToiletforholdKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UdestuearealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdlejningsforholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UdlejningsforholdKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UdnyttetTagarealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarmeinstallationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarmeinstallationKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VejkodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VejnavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> XKoordinatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YKoordinatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YdervaegsmaterialeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YdervaegsmaterialeKodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonekodeKodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalBeboelseslejlPaaEjendommen {
            get {
                return this.AntalBeboelseslejlPaaEjendommenField;
            }
            set {
                if ((this.AntalBeboelseslejlPaaEjendommenField.Equals(value) != true)) {
                    this.AntalBeboelseslejlPaaEjendommenField = value;
                    this.RaisePropertyChanged("AntalBeboelseslejlPaaEjendommen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalBeboelseslejligheder {
            get {
                return this.AntalBeboelseslejlighederField;
            }
            set {
                if ((this.AntalBeboelseslejlighederField.Equals(value) != true)) {
                    this.AntalBeboelseslejlighederField = value;
                    this.RaisePropertyChanged("AntalBeboelseslejligheder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalBygningerPaaEjendommen {
            get {
                return this.AntalBygningerPaaEjendommenField;
            }
            set {
                if ((this.AntalBygningerPaaEjendommenField.Equals(value) != true)) {
                    this.AntalBygningerPaaEjendommenField = value;
                    this.RaisePropertyChanged("AntalBygningerPaaEjendommen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalEjerlejlPaaEjendommen {
            get {
                return this.AntalEjerlejlPaaEjendommenField;
            }
            set {
                if ((this.AntalEjerlejlPaaEjendommenField.Equals(value) != true)) {
                    this.AntalEjerlejlPaaEjendommenField = value;
                    this.RaisePropertyChanged("AntalEjerlejlPaaEjendommen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalEnhederPaaEjendommen {
            get {
                return this.AntalEnhederPaaEjendommenField;
            }
            set {
                if ((this.AntalEnhederPaaEjendommenField.Equals(value) != true)) {
                    this.AntalEnhederPaaEjendommenField = value;
                    this.RaisePropertyChanged("AntalEnhederPaaEjendommen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalErhvervsenhederPaaEjendommen {
            get {
                return this.AntalErhvervsenhederPaaEjendommenField;
            }
            set {
                if ((this.AntalErhvervsenhederPaaEjendommenField.Equals(value) != true)) {
                    this.AntalErhvervsenhederPaaEjendommenField = value;
                    this.RaisePropertyChanged("AntalErhvervsenhederPaaEjendommen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalEtagerIBygning {
            get {
                return this.AntalEtagerIBygningField;
            }
            set {
                if ((this.AntalEtagerIBygningField.Equals(value) != true)) {
                    this.AntalEtagerIBygningField = value;
                    this.RaisePropertyChanged("AntalEtagerIBygning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalSmaabygninger {
            get {
                return this.AntalSmaabygningerField;
            }
            set {
                if ((this.AntalSmaabygningerField.Equals(value) != true)) {
                    this.AntalSmaabygningerField = value;
                    this.RaisePropertyChanged("AntalSmaabygninger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AntalVaerelser {
            get {
                return this.AntalVaerelserField;
            }
            set {
                if ((this.AntalVaerelserField.Equals(value) != true)) {
                    this.AntalVaerelserField = value;
                    this.RaisePropertyChanged("AntalVaerelser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ArealAfSmaabygninger {
            get {
                return this.ArealAfSmaabygningerField;
            }
            set {
                if ((this.ArealAfSmaabygningerField.Equals(value) != true)) {
                    this.ArealAfSmaabygningerField = value;
                    this.RaisePropertyChanged("ArealAfSmaabygninger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Badeforhold {
            get {
                return this.BadeforholdField;
            }
            set {
                if ((object.ReferenceEquals(this.BadeforholdField, value) != true)) {
                    this.BadeforholdField = value;
                    this.RaisePropertyChanged("Badeforhold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BadeforholdKode {
            get {
                return this.BadeforholdKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BadeforholdKodeField, value) != true)) {
                    this.BadeforholdKodeField = value;
                    this.RaisePropertyChanged("BadeforholdKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BeboetAreal {
            get {
                return this.BeboetArealField;
            }
            set {
                if ((this.BeboetArealField.Equals(value) != true)) {
                    this.BeboetArealField = value;
                    this.RaisePropertyChanged("BeboetAreal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BebyggetAreal {
            get {
                return this.BebyggetArealField;
            }
            set {
                if ((this.BebyggetArealField.Equals(value) != true)) {
                    this.BebyggetArealField = value;
                    this.RaisePropertyChanged("BebyggetAreal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beliggenhed {
            get {
                return this.BeliggenhedField;
            }
            set {
                if ((object.ReferenceEquals(this.BeliggenhedField, value) != true)) {
                    this.BeliggenhedField = value;
                    this.RaisePropertyChanged("Beliggenhed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BygningensAfloebsforhold {
            get {
                return this.BygningensAfloebsforholdField;
            }
            set {
                if ((object.ReferenceEquals(this.BygningensAfloebsforholdField, value) != true)) {
                    this.BygningensAfloebsforholdField = value;
                    this.RaisePropertyChanged("BygningensAfloebsforhold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BygningensAfloebsforholdKode {
            get {
                return this.BygningensAfloebsforholdKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BygningensAfloebsforholdKodeField, value) != true)) {
                    this.BygningensAfloebsforholdKodeField = value;
                    this.RaisePropertyChanged("BygningensAfloebsforholdKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BygningensAnvendelse {
            get {
                return this.BygningensAnvendelseField;
            }
            set {
                if ((object.ReferenceEquals(this.BygningensAnvendelseField, value) != true)) {
                    this.BygningensAnvendelseField = value;
                    this.RaisePropertyChanged("BygningensAnvendelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BygningensAnvendelseKode {
            get {
                return this.BygningensAnvendelseKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BygningensAnvendelseKodeField, value) != true)) {
                    this.BygningensAnvendelseKodeField = value;
                    this.RaisePropertyChanged("BygningensAnvendelseKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BygningensVandforsyning {
            get {
                return this.BygningensVandforsyningField;
            }
            set {
                if ((object.ReferenceEquals(this.BygningensVandforsyningField, value) != true)) {
                    this.BygningensVandforsyningField = value;
                    this.RaisePropertyChanged("BygningensVandforsyning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BygningensVandforsyningKode {
            get {
                return this.BygningensVandforsyningKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BygningensVandforsyningKodeField, value) != true)) {
                    this.BygningensVandforsyningKodeField = value;
                    this.RaisePropertyChanged("BygningensVandforsyningKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Bygningsnr {
            get {
                return this.BygningsnrField;
            }
            set {
                if ((this.BygningsnrField.Equals(value) != true)) {
                    this.BygningsnrField = value;
                    this.RaisePropertyChanged("Bygningsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeltaStatuskode {
            get {
                return this.DeltaStatuskodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeltaStatuskodeField, value) != true)) {
                    this.DeltaStatuskodeField = value;
                    this.RaisePropertyChanged("DeltaStatuskode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Doer {
            get {
                return this.DoerField;
            }
            set {
                if ((object.ReferenceEquals(this.DoerField, value) != true)) {
                    this.DoerField = value;
                    this.RaisePropertyChanged("Doer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EjendommensAfloebsforhold {
            get {
                return this.EjendommensAfloebsforholdField;
            }
            set {
                if ((object.ReferenceEquals(this.EjendommensAfloebsforholdField, value) != true)) {
                    this.EjendommensAfloebsforholdField = value;
                    this.RaisePropertyChanged("EjendommensAfloebsforhold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EjendommensAfloebsforholdKode {
            get {
                return this.EjendommensAfloebsforholdKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EjendommensAfloebsforholdKodeField, value) != true)) {
                    this.EjendommensAfloebsforholdKodeField = value;
                    this.RaisePropertyChanged("EjendommensAfloebsforholdKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EjendommensVandforsyning {
            get {
                return this.EjendommensVandforsyningField;
            }
            set {
                if ((object.ReferenceEquals(this.EjendommensVandforsyningField, value) != true)) {
                    this.EjendommensVandforsyningField = value;
                    this.RaisePropertyChanged("EjendommensVandforsyning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EjendommensVandforsyningKode {
            get {
                return this.EjendommensVandforsyningKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EjendommensVandforsyningKodeField, value) != true)) {
                    this.EjendommensVandforsyningKodeField = value;
                    this.RaisePropertyChanged("EjendommensVandforsyningKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ejerlav {
            get {
                return this.EjerlavField;
            }
            set {
                if ((object.ReferenceEquals(this.EjerlavField, value) != true)) {
                    this.EjerlavField = value;
                    this.RaisePropertyChanged("Ejerlav");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnhedAnvendelse {
            get {
                return this.EnhedAnvendelseField;
            }
            set {
                if ((object.ReferenceEquals(this.EnhedAnvendelseField, value) != true)) {
                    this.EnhedAnvendelseField = value;
                    this.RaisePropertyChanged("EnhedAnvendelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnhedAnvendelseKode {
            get {
                return this.EnhedAnvendelseKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnhedAnvendelseKodeField, value) != true)) {
                    this.EnhedAnvendelseKodeField = value;
                    this.RaisePropertyChanged("EnhedAnvendelseKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EnhedensAreal {
            get {
                return this.EnhedensArealField;
            }
            set {
                if ((this.EnhedensArealField.Equals(value) != true)) {
                    this.EnhedensArealField = value;
                    this.RaisePropertyChanged("EnhedensAreal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EnhedsId {
            get {
                return this.EnhedsIdField;
            }
            set {
                if ((this.EnhedsIdField.Equals(value) != true)) {
                    this.EnhedsIdField = value;
                    this.RaisePropertyChanged("EnhedsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Erhvervsareal {
            get {
                return this.ErhvervsarealField;
            }
            set {
                if ((this.ErhvervsarealField.Equals(value) != true)) {
                    this.ErhvervsarealField = value;
                    this.RaisePropertyChanged("Erhvervsareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsrEjendomsnr {
            get {
                return this.EsrEjendomsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.EsrEjendomsnrField, value) != true)) {
                    this.EsrEjendomsnrField = value;
                    this.RaisePropertyChanged("EsrEjendomsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etage {
            get {
                return this.EtageField;
            }
            set {
                if ((object.ReferenceEquals(this.EtageField, value) != true)) {
                    this.EtageField = value;
                    this.RaisePropertyChanged("Etage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fredningsforhold {
            get {
                return this.FredningsforholdField;
            }
            set {
                if ((object.ReferenceEquals(this.FredningsforholdField, value) != true)) {
                    this.FredningsforholdField = value;
                    this.RaisePropertyChanged("Fredningsforhold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FredningsforholdKode {
            get {
                return this.FredningsforholdKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FredningsforholdKodeField, value) != true)) {
                    this.FredningsforholdKodeField = value;
                    this.RaisePropertyChanged("FredningsforholdKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Husnummer {
            get {
                return this.HusnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.HusnummerField, value) != true)) {
                    this.HusnummerField = value;
                    this.RaisePropertyChanged("Husnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KVHX {
            get {
                return this.KVHXField;
            }
            set {
                if ((object.ReferenceEquals(this.KVHXField, value) != true)) {
                    this.KVHXField = value;
                    this.RaisePropertyChanged("KVHX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Kaelderareal {
            get {
                return this.KaelderarealField;
            }
            set {
                if ((this.KaelderarealField.Equals(value) != true)) {
                    this.KaelderarealField = value;
                    this.RaisePropertyChanged("Kaelderareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Koekken {
            get {
                return this.KoekkenField;
            }
            set {
                if ((object.ReferenceEquals(this.KoekkenField, value) != true)) {
                    this.KoekkenField = value;
                    this.RaisePropertyChanged("Koekken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KoekkenKode {
            get {
                return this.KoekkenKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.KoekkenKodeField, value) != true)) {
                    this.KoekkenKodeField = value;
                    this.RaisePropertyChanged("KoekkenKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KommuneKode {
            get {
                return this.KommuneKodeField;
            }
            set {
                if ((this.KommuneKodeField.Equals(value) != true)) {
                    this.KommuneKodeField = value;
                    this.RaisePropertyChanged("KommuneKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matrikelareal {
            get {
                return this.MatrikelarealField;
            }
            set {
                if ((object.ReferenceEquals(this.MatrikelarealField, value) != true)) {
                    this.MatrikelarealField = value;
                    this.RaisePropertyChanged("Matrikelareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matrikelbogstav {
            get {
                return this.MatrikelbogstavField;
            }
            set {
                if ((object.ReferenceEquals(this.MatrikelbogstavField, value) != true)) {
                    this.MatrikelbogstavField = value;
                    this.RaisePropertyChanged("Matrikelbogstav");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matrikelnr {
            get {
                return this.MatrikelnrField;
            }
            set {
                if ((object.ReferenceEquals(this.MatrikelnrField, value) != true)) {
                    this.MatrikelnrField = value;
                    this.RaisePropertyChanged("Matrikelnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OmTilbygningsaar {
            get {
                return this.OmTilbygningsaarField;
            }
            set {
                if ((this.OmTilbygningsaarField.Equals(value) != true)) {
                    this.OmTilbygningsaarField = value;
                    this.RaisePropertyChanged("OmTilbygningsaar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Opdateringsdato {
            get {
                return this.OpdateringsdatoField;
            }
            set {
                if ((this.OpdateringsdatoField.Equals(value) != true)) {
                    this.OpdateringsdatoField = value;
                    this.RaisePropertyChanged("Opdateringsdato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Opfoerelsesaar {
            get {
                return this.OpfoerelsesaarField;
            }
            set {
                if ((this.OpfoerelsesaarField.Equals(value) != true)) {
                    this.OpfoerelsesaarField = value;
                    this.RaisePropertyChanged("Opfoerelsesaar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opvarmningsform {
            get {
                return this.OpvarmningsformField;
            }
            set {
                if ((object.ReferenceEquals(this.OpvarmningsformField, value) != true)) {
                    this.OpvarmningsformField = value;
                    this.RaisePropertyChanged("Opvarmningsform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpvarmningsformKode {
            get {
                return this.OpvarmningsformKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpvarmningsformKodeField, value) != true)) {
                    this.OpvarmningsformKodeField = value;
                    this.RaisePropertyChanged("OpvarmningsformKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postdistriktsnavn {
            get {
                return this.PostdistriktsnavnField;
            }
            set {
                if ((object.ReferenceEquals(this.PostdistriktsnavnField, value) != true)) {
                    this.PostdistriktsnavnField = value;
                    this.RaisePropertyChanged("Postdistriktsnavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postnummer {
            get {
                return this.PostnummerField;
            }
            set {
                if ((object.ReferenceEquals(this.PostnummerField, value) != true)) {
                    this.PostnummerField = value;
                    this.RaisePropertyChanged("Postnummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletBebyggetAreal {
            get {
                return this.SamletBebyggetArealField;
            }
            set {
                if ((this.SamletBebyggetArealField.Equals(value) != true)) {
                    this.SamletBebyggetArealField = value;
                    this.RaisePropertyChanged("SamletBebyggetAreal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletBoligareal {
            get {
                return this.SamletBoligarealField;
            }
            set {
                if ((this.SamletBoligarealField.Equals(value) != true)) {
                    this.SamletBoligarealField = value;
                    this.RaisePropertyChanged("SamletBoligareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletBoligarealIBygning {
            get {
                return this.SamletBoligarealIBygningField;
            }
            set {
                if ((this.SamletBoligarealIBygningField.Equals(value) != true)) {
                    this.SamletBoligarealIBygningField = value;
                    this.RaisePropertyChanged("SamletBoligarealIBygning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletBygningsareal {
            get {
                return this.SamletBygningsarealField;
            }
            set {
                if ((this.SamletBygningsarealField.Equals(value) != true)) {
                    this.SamletBygningsarealField = value;
                    this.RaisePropertyChanged("SamletBygningsareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletBygningsareal2 {
            get {
                return this.SamletBygningsareal2Field;
            }
            set {
                if ((this.SamletBygningsareal2Field.Equals(value) != true)) {
                    this.SamletBygningsareal2Field = value;
                    this.RaisePropertyChanged("SamletBygningsareal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletErhvervsAreal {
            get {
                return this.SamletErhvervsArealField;
            }
            set {
                if ((this.SamletErhvervsArealField.Equals(value) != true)) {
                    this.SamletErhvervsArealField = value;
                    this.RaisePropertyChanged("SamletErhvervsAreal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletErhvervsarealIBygning {
            get {
                return this.SamletErhvervsarealIBygningField;
            }
            set {
                if ((this.SamletErhvervsarealIBygningField.Equals(value) != true)) {
                    this.SamletErhvervsarealIBygningField = value;
                    this.RaisePropertyChanged("SamletErhvervsarealIBygning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SamletTagareal {
            get {
                return this.SamletTagarealField;
            }
            set {
                if ((this.SamletTagarealField.Equals(value) != true)) {
                    this.SamletTagarealField = value;
                    this.RaisePropertyChanged("SamletTagareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stednavn {
            get {
                return this.StednavnField;
            }
            set {
                if ((object.ReferenceEquals(this.StednavnField, value) != true)) {
                    this.StednavnField = value;
                    this.RaisePropertyChanged("Stednavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplerendeVarmekilde {
            get {
                return this.SupplerendeVarmekildeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplerendeVarmekildeField, value) != true)) {
                    this.SupplerendeVarmekildeField = value;
                    this.RaisePropertyChanged("SupplerendeVarmekilde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplerendeVarmekildeKode {
            get {
                return this.SupplerendeVarmekildeKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplerendeVarmekildeKodeField, value) != true)) {
                    this.SupplerendeVarmekildeKodeField = value;
                    this.RaisePropertyChanged("SupplerendeVarmekildeKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tagmateriale {
            get {
                return this.TagmaterialeField;
            }
            set {
                if ((object.ReferenceEquals(this.TagmaterialeField, value) != true)) {
                    this.TagmaterialeField = value;
                    this.RaisePropertyChanged("Tagmateriale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagmaterialeKode {
            get {
                return this.TagmaterialeKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TagmaterialeKodeField, value) != true)) {
                    this.TagmaterialeKodeField = value;
                    this.RaisePropertyChanged("TagmaterialeKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TilnaermetEtageareal {
            get {
                return this.TilnaermetEtagearealField;
            }
            set {
                if ((this.TilnaermetEtagearealField.Equals(value) != true)) {
                    this.TilnaermetEtagearealField = value;
                    this.RaisePropertyChanged("TilnaermetEtageareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Toiletforhold {
            get {
                return this.ToiletforholdField;
            }
            set {
                if ((object.ReferenceEquals(this.ToiletforholdField, value) != true)) {
                    this.ToiletforholdField = value;
                    this.RaisePropertyChanged("Toiletforhold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToiletforholdKode {
            get {
                return this.ToiletforholdKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ToiletforholdKodeField, value) != true)) {
                    this.ToiletforholdKodeField = value;
                    this.RaisePropertyChanged("ToiletforholdKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Udestueareal {
            get {
                return this.UdestuearealField;
            }
            set {
                if ((this.UdestuearealField.Equals(value) != true)) {
                    this.UdestuearealField = value;
                    this.RaisePropertyChanged("Udestueareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Udlejningsforhold {
            get {
                return this.UdlejningsforholdField;
            }
            set {
                if ((object.ReferenceEquals(this.UdlejningsforholdField, value) != true)) {
                    this.UdlejningsforholdField = value;
                    this.RaisePropertyChanged("Udlejningsforhold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UdlejningsforholdKode {
            get {
                return this.UdlejningsforholdKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UdlejningsforholdKodeField, value) != true)) {
                    this.UdlejningsforholdKodeField = value;
                    this.RaisePropertyChanged("UdlejningsforholdKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UdnyttetTagareal {
            get {
                return this.UdnyttetTagarealField;
            }
            set {
                if ((this.UdnyttetTagarealField.Equals(value) != true)) {
                    this.UdnyttetTagarealField = value;
                    this.RaisePropertyChanged("UdnyttetTagareal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varmeinstallation {
            get {
                return this.VarmeinstallationField;
            }
            set {
                if ((object.ReferenceEquals(this.VarmeinstallationField, value) != true)) {
                    this.VarmeinstallationField = value;
                    this.RaisePropertyChanged("Varmeinstallation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VarmeinstallationKode {
            get {
                return this.VarmeinstallationKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VarmeinstallationKodeField, value) != true)) {
                    this.VarmeinstallationKodeField = value;
                    this.RaisePropertyChanged("VarmeinstallationKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vejkode {
            get {
                return this.VejkodeField;
            }
            set {
                if ((this.VejkodeField.Equals(value) != true)) {
                    this.VejkodeField = value;
                    this.RaisePropertyChanged("Vejkode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vejnavn {
            get {
                return this.VejnavnField;
            }
            set {
                if ((object.ReferenceEquals(this.VejnavnField, value) != true)) {
                    this.VejnavnField = value;
                    this.RaisePropertyChanged("Vejnavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> XKoordinat {
            get {
                return this.XKoordinatField;
            }
            set {
                if ((this.XKoordinatField.Equals(value) != true)) {
                    this.XKoordinatField = value;
                    this.RaisePropertyChanged("XKoordinat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> YKoordinat {
            get {
                return this.YKoordinatField;
            }
            set {
                if ((this.YKoordinatField.Equals(value) != true)) {
                    this.YKoordinatField = value;
                    this.RaisePropertyChanged("YKoordinat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ydervaegsmateriale {
            get {
                return this.YdervaegsmaterialeField;
            }
            set {
                if ((object.ReferenceEquals(this.YdervaegsmaterialeField, value) != true)) {
                    this.YdervaegsmaterialeField = value;
                    this.RaisePropertyChanged("Ydervaegsmateriale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YdervaegsmaterialeKode {
            get {
                return this.YdervaegsmaterialeKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.YdervaegsmaterialeKodeField, value) != true)) {
                    this.YdervaegsmaterialeKodeField = value;
                    this.RaisePropertyChanged("YdervaegsmaterialeKode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZonekodeKode {
            get {
                return this.ZonekodeKodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonekodeKodeField, value) != true)) {
                    this.ZonekodeKodeField = value;
                    this.RaisePropertyChanged("ZonekodeKode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TIABBRClient.IKvhxBackendService")]
    public interface IKvhxBackendService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/ConvertAdressToSpecificKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/ConvertAdressToSpecificKvhxResponse")]
        string ConvertAdressToSpecificKvhx(string kvhxType, int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/ConvertAdressToSpecificKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/ConvertAdressToSpecificKvhxResponse")]
        System.Threading.Tasks.Task<string> ConvertAdressToSpecificKvhxAsync(string kvhxType, int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/ConvertAdressToKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/ConvertAdressToKvhxResponse")]
        string ConvertAdressToKvhx(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/ConvertAdressToKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/ConvertAdressToKvhxResponse")]
        System.Threading.Tasks.Task<string> ConvertAdressToKvhxAsync(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/GetBbrDataFromAddress", ReplyAction="http://tempuri.org/IKvhxBackendService/GetBbrDataFromAddressResponse")]
        GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse GetBbrDataFromAddress(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/GetBbrDataFromAddress", ReplyAction="http://tempuri.org/IKvhxBackendService/GetBbrDataFromAddressResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> GetBbrDataFromAddressAsync(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/GetBbrDataFromCprKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/GetBbrDataFromCprKvhxResponse")]
        GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse GetBbrDataFromCprKvhx(string cprKvhx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/GetBbrDataFromCprKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/GetBbrDataFromCprKvhxResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> GetBbrDataFromCprKvhxAsync(string cprKvhx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/GetBbrDataFromKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/GetBbrDataFromKvhxResponse")]
        GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse GetBbrDataFromKvhx(string kvhx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/GetBbrDataFromKvhx", ReplyAction="http://tempuri.org/IKvhxBackendService/GetBbrDataFromKvhxResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> GetBbrDataFromKvhxAsync(string kvhx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/SearchBbrDataFromAddress", ReplyAction="http://tempuri.org/IKvhxBackendService/SearchBbrDataFromAddressResponse")]
        GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse SearchBbrDataFromAddress(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment, int maxRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKvhxBackendService/SearchBbrDataFromAddress", ReplyAction="http://tempuri.org/IKvhxBackendService/SearchBbrDataFromAddressResponse")]
        System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> SearchBbrDataFromAddressAsync(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment, int maxRows);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKvhxBackendServiceChannel : GF.Service.FandP.PriceCalculator.TIABBRClient.IKvhxBackendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KvhxBackendServiceClient : System.ServiceModel.ClientBase<GF.Service.FandP.PriceCalculator.TIABBRClient.IKvhxBackendService>, GF.Service.FandP.PriceCalculator.TIABBRClient.IKvhxBackendService {
        
        public KvhxBackendServiceClient() {
        }
        
        public KvhxBackendServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KvhxBackendServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KvhxBackendServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KvhxBackendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertAdressToSpecificKvhx(string kvhxType, int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment) {
            return base.Channel.ConvertAdressToSpecificKvhx(kvhxType, postArea, streetName, streetNumber, streetLetter, floor, floorApartment);
        }
        
        public System.Threading.Tasks.Task<string> ConvertAdressToSpecificKvhxAsync(string kvhxType, int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment) {
            return base.Channel.ConvertAdressToSpecificKvhxAsync(kvhxType, postArea, streetName, streetNumber, streetLetter, floor, floorApartment);
        }
        
        public string ConvertAdressToKvhx(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment) {
            return base.Channel.ConvertAdressToKvhx(postArea, streetName, streetNumber, streetLetter, floor, floorApartment);
        }
        
        public System.Threading.Tasks.Task<string> ConvertAdressToKvhxAsync(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment) {
            return base.Channel.ConvertAdressToKvhxAsync(postArea, streetName, streetNumber, streetLetter, floor, floorApartment);
        }
        
        public GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse GetBbrDataFromAddress(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment) {
            return base.Channel.GetBbrDataFromAddress(postArea, streetName, streetNumber, streetLetter, floor, floorApartment);
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> GetBbrDataFromAddressAsync(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment) {
            return base.Channel.GetBbrDataFromAddressAsync(postArea, streetName, streetNumber, streetLetter, floor, floorApartment);
        }
        
        public GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse GetBbrDataFromCprKvhx(string cprKvhx) {
            return base.Channel.GetBbrDataFromCprKvhx(cprKvhx);
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> GetBbrDataFromCprKvhxAsync(string cprKvhx) {
            return base.Channel.GetBbrDataFromCprKvhxAsync(cprKvhx);
        }
        
        public GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse GetBbrDataFromKvhx(string kvhx) {
            return base.Channel.GetBbrDataFromKvhx(kvhx);
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> GetBbrDataFromKvhxAsync(string kvhx) {
            return base.Channel.GetBbrDataFromKvhxAsync(kvhx);
        }
        
        public GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse SearchBbrDataFromAddress(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment, int maxRows) {
            return base.Channel.SearchBbrDataFromAddress(postArea, streetName, streetNumber, streetLetter, floor, floorApartment, maxRows);
        }
        
        public System.Threading.Tasks.Task<GF.Service.FandP.PriceCalculator.TIABBRClient.BbrDataResponse> SearchBbrDataFromAddressAsync(int postArea, string streetName, string streetNumber, string streetLetter, string floor, string floorApartment, int maxRows) {
            return base.Channel.SearchBbrDataFromAddressAsync(postArea, streetName, streetNumber, streetLetter, floor, floorApartment, maxRows);
        }
    }
}
