//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.FandP.PriceCalc.PriceCalcClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PriceCalcClient.IPriceCalcService")]
    public interface IPriceCalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPriceCalcService/CalculatePrice", ReplyAction="http://tempuri.org/IPriceCalcService/CalculatePriceResponse")]
        bool CalculatePrice(out string xmlResponse, out string error, string xmlRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPriceCalcServiceChannel : UnitTest.FandP.PriceCalc.PriceCalcClient.IPriceCalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceCalcServiceClient : System.ServiceModel.ClientBase<UnitTest.FandP.PriceCalc.PriceCalcClient.IPriceCalcService>, UnitTest.FandP.PriceCalc.PriceCalcClient.IPriceCalcService {
        
        public PriceCalcServiceClient() {
        }
        
        public PriceCalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceCalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceCalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceCalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CalculatePrice(out string xmlResponse, out string error, string xmlRequest) {
            return base.Channel.CalculatePrice(out xmlResponse, out error, xmlRequest);
        }
    }
}
